#!/usr/bin/env bun
// Puts the transformed core into the application's database (K-112). Writes the SQL either way,
// because production is applied by hand from that file and never from here.
import { Database } from 'bun:sqlite'
import { join } from 'node:path'
import { OUT, ensureOut } from './lib'
import { assertLocalTarget, assertNotProduction } from '../tests/helpers/seed'

// The tables the identity import owns. Anything else in the target is the application's.
export const LOADED_TABLES = ['users', 'role_grants', 'totp_secrets', 'recovery_codes'] as const

const COLUMNS: Record<string, string[]> = {
  users: [
    'id', 'email', 'name', 'password', 'google_sub', 'pending_google_email', 'verified',
    'disabled', 'session_epoch', 'anonymised_at', 'last_login_at', 'created_at', 'updated_at',
  ],
  role_grants: ['id', 'user_id', 'role', 'expires_at', 'granted_by', 'granted_at', 'note', 'expiry_warned_at'],
  totp_secrets: ['user_id', 'secret', 'confirmed_at', 'last_used_step', 'created_at'],
  recovery_codes: ['id', 'user_id', 'code_hash', 'used_at'],
}

// What identifies a row on a second run. A grant keeps the id it was first given, because the
// transform mints a new one every time and the person plus the role is what is actually the same.
const CONFLICT: Record<string, string[]> = {
  users: ['id'],
  role_grants: ['user_id', 'role'],
  totp_secrets: ['user_id'],
  recovery_codes: [],
}

function literal(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  return `'${String(value).replaceAll('\'', '\'\'')}'`
}

function upsert(table: string, row: Record<string, unknown>): string {
  const columns = COLUMNS[table]!
  const values = columns.map(column => literal(row[column])).join(', ')
  const keys = CONFLICT[table]!
  const insert = `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values})`
  if (!keys.length) return `${insert};`

  const updates = columns.filter(column => !keys.includes(column))
  return `${insert} ON CONFLICT (${keys.join(', ')}) DO UPDATE SET ${updates.map(column => `${column} = excluded.${column}`).join(', ')};`
}

// Recovery codes have no key that survives a re-mint, so a person's set is replaced whole. That
// matches how the application mints them: a new set retires the old one (A-110 criterion 3).
function replaceCodes(core: Database): string[] {
  const owners = core.query<{ user_id: string }, []>('SELECT DISTINCT user_id FROM recovery_codes').all()
  return owners.map(owner => `DELETE FROM recovery_codes WHERE user_id = ${literal(owner.user_id)};`)
}

export function buildLoad(core: Database): string {
  const lines: string[] = [
    '-- Generated by migration/load.ts. Upserts by identity: running it twice updates, never doubles.',
    '-- It does not delete: a person or a grant that vanished upstream stays until somebody decides.',
  ]

  for (const table of LOADED_TABLES) {
    const rows = core.query<Record<string, unknown>, []>(`SELECT * FROM ${table}`).all()
    if (!rows.length) continue
    lines.push('', `-- ${table}: ${rows.length}`)
    if (table === 'recovery_codes') lines.push(...replaceCodes(core))
    for (const row of rows) lines.push(upsert(table, row))
  }

  return `${lines.join('\n')}\n`
}

export function applyLoad(sql: string, target: Database): void {
  target.transaction(() => target.exec(sql))()
}

export function loadedCounts(target: Database): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const table of LOADED_TABLES) {
    counts[table] = (target.query<{ n: number }, []>(`SELECT count(*) n FROM ${table}`).get() as { n: number }).n
  }
  return counts
}

// A target the load already half owns is fine; one holding people it has never heard of is not,
// because the id map is what stops a second run importing the estate again (0030).
export function unknownUsers(target: Database, ids: Set<string>): number {
  const held = target.query<{ id: string }, []>('SELECT id FROM users').all()
  return held.filter(row => !ids.has(row.id)).length
}

if (import.meta.main) {
  assertNotProduction()
  ensureOut()

  const core = new Database(join(OUT, 'unified.sqlite'), { readonly: true })
  const sql = buildLoad(core)
  const path = join(OUT, 'load.sql')
  await Bun.write(path, sql)
  console.log(`Wrote ${path} (${sql.split('\n').length} statements over ${LOADED_TABLES.length} tables).`)

  const applyTo = process.argv.slice(2).find(argument => !argument.startsWith('-'))
  if (!applyTo) {
    console.log('\nNo target given, so nothing was applied. To rehearse against a local database:')
    console.log('  bun migration/load.ts .data/db/sqlite.db')
    console.log('Production is applied by hand from the runbook, never from here.')
    core.close()
    process.exit(0)
  }

  // The same refusal the seed tooling makes: this writes people, so it may only write locally.
  assertLocalTarget(applyTo)
  const target = new Database(applyTo)
  applyLoad(sql, target)

  const counts = loadedCounts(target)
  console.log(`\nLoaded into ${applyTo}:`)
  for (const [table, count] of Object.entries(counts)) console.log(`  ${count} ${table}`)
  target.close()
  core.close()
}
