import type { AuditActionName } from './audit-actions'

// Which route is answerable for which entry. `check:audit` reads this, so a privileged mutation
// arriving without an audit write is a failed build rather than a missed review (J-101 criterion 5).

export interface Covered {
  route: string
  actions: AuditActionName[]
  // Files the route delegates its write to, because the entry is built there rather than here.
  via?: string[]
  exempt?: never
}

export interface Exempt {
  route: string
  actions?: never
  via?: never
  // Why this route records nothing. A reason, not a permission: it is read at review time.
  exempt: string
}

export type Coverage = Covered | Exempt

export const AUDIT_COVERAGE: Coverage[] = [
  // Module A: identity

  { route: 'server/api/account/close.post.ts', actions: ['account.erased'], via: ['server/utils/erasure.ts'] },
  { route: 'server/api/account/export.get.ts', actions: ['account.exported'] },
  { route: 'server/api/account/mfa/confirm.post.ts', actions: ['mfa.confirmed', 'mfa.recovery-codes.minted'] },
  {
    route: 'server/api/account/mfa/enrol.post.ts',
    exempt: 'an unconfirmed enrolment is not a second factor; confirming it is what is recorded',
  },
  { route: 'server/api/account/mfa/index.delete.ts', actions: ['mfa.removed'] },
  { route: 'server/api/account/mfa/recovery-codes.post.ts', actions: ['mfa.recovery-codes.minted'] },
  {
    route: 'server/api/admin/accounts/[id]/security.post.ts',
    actions: ['account.disabled', 'account.enabled', 'session.revoked', 'mfa.reset', 'account.erased.admin'],
    via: ['server/utils/erasure.ts'],
  },
  {
    route: 'server/api/admin/accounts/index.post.ts',
    actions: ['account.created.console', 'role.granted'],
    via: ['server/utils/accounts.ts'],
  },
  { route: 'server/api/admin/memberships/[id]/confirm.post.ts', actions: ['membership.confirmed'] },
  { route: 'server/api/admin/memberships/export.get.ts', actions: ['membership.exported'] },
  {
    route: 'server/api/admin/memberships/index.post.ts',
    actions: ['membership.granted', 'account.student-id.recorded'],
    via: ['server/utils/membership.ts'],
  },
  { route: 'server/api/admin/roles/index.delete.ts', actions: ['role.revoked'] },
  { route: 'server/api/admin/roles/index.post.ts', actions: ['role.granted'] },
  { route: 'server/api/auth/magic-link/consume.post.ts', actions: ['session.started.magic-link', 'mfa.challenged'] },
  {
    route: 'server/api/auth/magic-link/request.post.ts',
    exempt: 'issues a token and asks for a message; the send is recorded in notification_log',
  },
  {
    route: 'server/api/auth/mfa/challenge.post.ts',
    actions: ['session.started.totp', 'session.started.recovery-code', 'mfa.challenged'],
  },
  {
    route: 'server/api/auth/password/forgot.post.ts',
    exempt: 'issues a token and asks for a message; the send is recorded in notification_log',
  },
  { route: 'server/api/auth/password/reset.post.ts', actions: ['password.set', 'password.reset'] },
  { route: 'server/api/auth/register.post.ts', actions: ['account.registered'], via: ['server/utils/accounts.ts'] },
  { route: 'server/api/auth/sign-in.post.ts', actions: ['session.started', 'mfa.challenged'] },
  { route: 'server/api/account/methods/[id].delete.ts', actions: ['account.method.removed'] },
  { route: 'server/api/account/password.put.ts', actions: ['account.method.added', 'password.set'] },
  { route: 'server/api/account/email.put.ts', actions: ['account.email.changed', 'account.email.changed.admin'], via: ['server/utils/email-change.ts'] },
  { route: 'server/api/account/profile.put.ts', actions: ['account.profile.updated'], via: ['server/utils/profile.ts'] },
  { route: 'server/api/account/profile.get.ts', exempt: 'reads your own profile' },
  { route: 'server/api/account/methods/index.get.ts', exempt: 'reads what the account signs in with' },
  { route: 'server/api/auth/passkey/register.post.ts', actions: ['account.method.added'] },
  { route: 'server/api/auth/passkey/authenticate.post.ts', actions: ['session.started.passkey'] },
  { route: 'server/api/account/room-feed.get.ts', exempt: 'says whether your own feed exists' },
  { route: 'server/api/account/room-feed.post.ts', actions: ['account.calendar-feed.issued'] },
  { route: 'server/api/auth/sign-out.post.ts', exempt: 'ending your own session changes no record' },
  { route: 'server/api/auth/verify/index.post.ts', actions: ['account.verified'] },
  {
    route: 'server/api/auth/verify/resend.post.ts',
    exempt: 'issues a token and asks for a message; the send is recorded in notification_log',
  },
  { route: 'server/routes/auth/google.get.ts', actions: ['account.created.google', 'session.started.google'] },

  // Module C: spaces

  { route: 'server/api/rooms/availability.get.ts', exempt: 'reads what is already taken' },
  { route: 'server/api/rooms/policy.get.ts', exempt: 'reads the published booking rules' },
  { route: 'server/api/rooms/bookings/index.get.ts', exempt: 'reads the bookings you hold' },
  { route: 'server/api/rooms/bookings/[id]/cancel.post.ts', actions: ['room.booking.cancelled'] },
  { route: 'server/api/rooms/bookings/[id]/ics.get.ts', exempt: 'downloads a booking you already hold' },
  {
    route: 'server/routes/rooms/feed/[token]/calendar.ics.get.ts',
    exempt: 'reads your own bookings; a fetch is recorded on the token, not in the trail',
  },
  { route: 'server/api/rooms/requests.post.ts', actions: ['room.requested'] },
  { route: 'server/api/rooms/series.post.ts', actions: ['room.series.booked', 'room.series.requested'] },
  { route: 'server/api/rooms/bookings.post.ts', actions: ['room.booked'] },
  { route: 'server/api/admin/rooms/index.get.ts', exempt: 'reads the bookable estate' },
  { route: 'server/api/admin/rooms/queue.get.ts', exempt: 'reads what is waiting on a decision, ours and not' },
  { route: 'server/api/admin/rooms/requests/[id]/unlist.post.ts', actions: ['room.request.unlisted'] },
  { route: 'server/api/admin/rooms/external-requests/[id]/relist.post.ts', actions: ['external.request.relisted'] },
  {
    route: 'server/api/admin/rooms/requests/decide.post.ts',
    actions: ['room.request.approved', 'room.request.rejected'],
  },
  { route: 'server/api/admin/rooms/index.post.ts', actions: ['room.created'] },
  { route: 'server/api/admin/rooms/[id]/index.put.ts', actions: ['room.updated', 'room.hours.set'] },
  { route: 'server/api/admin/rooms/[id]/index.delete.ts', actions: ['room.updated'] },
  { route: 'server/api/admin/rooms/blackouts/index.get.ts', exempt: 'reads which rooms are shut' },
  { route: 'server/api/admin/rooms/blackouts/index.post.ts', actions: ['room.blackout.created'] },
  { route: 'server/api/admin/rooms/blackouts/[id].delete.ts', actions: ['room.blackout.removed'] },
  { route: 'server/api/admin/rooms/bookings/[id]/bump.post.ts', actions: ['room.booking.bumped'] },
  { route: 'server/api/admin/rooms/bookings/[id]/alternatives.get.ts', exempt: 'reads where a booking could go instead' },
  { route: 'server/api/admin/rooms/bookings/[id]/no-show.post.ts', actions: ['room.no-show.recorded'] },
  { route: 'server/api/admin/rooms/no-shows/[id]/withdraw.post.ts', actions: ['room.no-show.withdrawn'] },
  { route: 'server/api/rooms/standing.get.ts', exempt: 'reads your own record' },
  { route: 'server/api/rooms/external-spaces.get.ts', exempt: 'searches the rooms the SU manages' },
  { route: 'server/api/rooms/external-requests.get.ts', exempt: 'reads the unlisted rooms you asked for' },
  { route: 'server/api/rooms/external-requests.post.ts', actions: ['external.requested'] },
  { route: 'server/api/rooms/external-requests/[id]/cancel.post.ts', actions: ['external.request.cancelled'] },
  { route: 'server/api/admin/rooms/external-requests/[id]/submit.post.ts', actions: ['external.request.submitted'] },
  { route: 'server/api/admin/rooms/external-requests/[id]/assign.post.ts', actions: ['external.request.assigned'] },
  {
    route: 'server/api/admin/rooms/external-requests/[id]/refuse-assignment.post.ts',
    actions: ['external.request.assignment.refused'],
  },
  { route: 'server/api/admin/rooms/external-requests/[id]/reject.post.ts', actions: ['external.request.rejected'] },
  { route: 'server/api/admin/rooms/external-spaces/index.get.ts', exempt: 'reads the SU catalogue' },
  { route: 'server/api/admin/rooms/external-spaces/index.post.ts', actions: ['external.space.created'] },
  { route: 'server/api/admin/rooms/external-spaces/[id]/index.put.ts', actions: ['external.space.updated'] },
  { route: 'server/api/admin/rooms/external-spaces/[id]/notes/index.put.ts', actions: ['external.space.note.set'] },
  { route: 'server/api/admin/rooms/external-spaces/[id]/notes/[purpose].delete.ts', actions: ['external.space.note.removed'] },
  { route: 'server/api/admin/rooms/reports/utilisation.get.ts', exempt: 'reads booked hours against open hours' },
  { route: 'server/api/admin/rooms/reports/export.get.ts', exempt: 'the same figures as a file; no personal column is in it' },

  // Module D: ticketing

  { route: 'server/api/admin/ticket-types/index.get.ts', exempt: 'reads the ticket types, archived ones included' },
  { route: 'server/api/admin/ticket-types/index.post.ts', actions: ['ticket-type.created'] },
  { route: 'server/api/admin/ticket-types/[id]/index.put.ts', actions: ['ticket-type.updated', 'ticket-type.price.changed'] },
  { route: 'server/api/admin/ticket-types/[id]/archive.post.ts', actions: ['ticket-type.archived', 'ticket-type.restored'] },
  { route: 'server/api/admin/ticket-types/[id]/index.delete.ts', actions: ['ticket-type.deleted'] },
  { route: 'server/api/admin/pass-types/index.get.ts', exempt: 'reads the pass products' },
  { route: 'server/api/admin/pass-types/index.post.ts', actions: ['pass-type.created'] },
  { route: 'server/api/admin/pass-types/[id]/index.get.ts', exempt: 'reads one pass product and the shows it may cover' },
  { route: 'server/api/admin/pass-types/[id]/index.put.ts', actions: ['pass-type.updated'] },
  { route: 'server/api/admin/pass-types/[id]/shows.put.ts', actions: ['pass-type.shows.updated'] },
  { route: 'server/api/admin/pass-types/[id]/index.delete.ts', actions: ['pass-type.deleted'] },
  { route: 'server/api/box-office/desk/passes/index.get.ts', exempt: 'reads what may be sold; nothing is written' },
  { route: 'server/api/box-office/desk/passes/buyers.get.ts', exempt: 'searches accounts by name or email; nothing is written' },
  { route: 'server/api/box-office/desk/passes/[passTypeId]/requests.get.ts', exempt: 'reads pending requests; nothing is written' },
  {
    route: 'server/api/box-office/desk/passes/index.post.ts',
    actions: ['pass.issued', 'pass.request.fulfilled'],
    via: ['server/utils/pass-issue.ts'],
  },
  { route: 'server/api/account/passes/index.get.ts', exempt: 'reads the caller\'s own held passes and requests' },
  {
    route: 'server/api/account/passes/request.post.ts',
    actions: ['pass.request.created'],
    via: ['server/utils/pass-issue.ts'],
  },
  { route: 'server/api/passes/current.get.ts', exempt: 'reads the pass the cookie names; nothing is written' },
  { route: 'server/routes/passes/[token].get.ts', exempt: 'exchanges a token for a cookie; nothing is written' },
  { route: 'server/api/admin/programme/shows.get.ts', exempt: 'reads the show picker, drafts included' },
  { route: 'server/api/admin/venues/index.get.ts', exempt: 'reads the venues a performance may be put in' },
  { route: 'server/api/admin/shows/index.get.ts', exempt: 'reads the programme, drafts included' },
  { route: 'server/api/admin/shows/index.post.ts', actions: ['show.created'] },
  { route: 'server/api/admin/shows/[id]/index.get.ts', exempt: 'reads one show and its performances' },
  { route: 'server/api/admin/shows/[id]/index.put.ts', actions: ['show.updated'] },
  { route: 'server/api/admin/shows/[id]/publish.post.ts', actions: ['show.published', 'show.unpublished'] },
  { route: 'server/api/admin/shows/[id]/index.delete.ts', actions: ['show.deleted'] },
  { route: 'server/api/admin/shows/[id]/performances.post.ts', actions: ['performance.created'] },
  { route: 'server/api/admin/performances/[id]/index.put.ts', actions: ['performance.updated'] },
  { route: 'server/api/admin/performances/[id]/sale.post.ts', actions: ['performance.on-sale', 'performance.off-sale'] },
  { route: 'server/api/admin/performances/[id]/cancel.post.ts', actions: ['performance.cancelled'] },
  { route: 'server/api/admin/performances/[id]/index.delete.ts', actions: ['performance.deleted'] },
  { route: 'server/api/admin/shows/[id]/warnings.put.ts', actions: ['show.warnings.set'] },
  { route: 'server/api/admin/shows/[id]/prices.get.ts', exempt: 'reads this show\'s price chain' },
  { route: 'server/api/admin/shows/[id]/prices.put.ts', actions: ['show.prices.set'] },
  { route: 'server/api/admin/performances/[id]/prices.get.ts', exempt: 'reads this performance\'s price chain' },
  { route: 'server/api/admin/performances/[id]/prices.put.ts', actions: ['performance.prices.set'] },
  { route: 'server/api/admin/content-warnings/index.get.ts', exempt: 'reads the warning vocabulary' },
  { route: 'server/api/admin/content-warnings/index.post.ts', actions: ['content-warning.created'] },
  { route: 'server/api/admin/content-warnings/[id]/index.put.ts', actions: ['content-warning.updated'] },
  { route: 'server/api/admin/content-warnings/[id]/index.delete.ts', actions: ['content-warning.deleted'] },
  { route: 'server/api/admin/access-profiles/index.get.ts', exempt: 'reads declarations without the encrypted payload' },
  { route: 'server/api/admin/access-profiles/[userId]/index.get.ts', exempt: 'reads one declaration in full, for the officer deciding it' },
  { route: 'server/api/admin/access-profiles/[userId]/verify.post.ts', actions: ['access-profile.verified'], via: ['server/utils/access-profiles.ts'] },
  { route: 'server/api/admin/access-profiles/[userId]/decline.post.ts', actions: ['access-profile.declined'], via: ['server/utils/access-profiles.ts'] },
  { route: 'server/api/account/access-profile.get.ts', exempt: 'reads the caller\'s own declaration' },
  { route: 'server/api/account/access-profile.put.ts', actions: ['access-profile.updated'], via: ['server/utils/access-profiles.ts'] },
  { route: 'server/api/account/access-profile/withdraw.post.ts', actions: ['access-profile.withdrawn'], via: ['server/utils/access-profiles.ts'] },
  {
    route: 'server/api/reservations.post.ts',
    actions: ['account.created.guest'],
    via: ['server/utils/reservations.ts'],
  },
  { route: 'server/api/performances/[id]/booking.get.ts', exempt: 'reads what the booking form needs; nothing is written' },
  { route: 'server/api/reservations/resend.post.ts', exempt: 'sends a message; the send is recorded in notification_log' },
  { route: 'server/routes/qr/[token].get.ts', exempt: 'exchanges a token for a cookie; nothing is written' },
  { route: 'server/api/qr/edit-options.get.ts', exempt: 'reads what the edit form needs; nothing is written' },
  {
    route: 'server/api/qr/tickets.put.ts',
    actions: ['reservation.tickets-changed'],
    via: ['server/utils/reservations.ts'],
  },
  {
    route: 'server/api/qr/cancel.post.ts',
    actions: ['reservation.cancelled'],
    via: ['server/utils/reservations.ts'],
  },
  { route: 'server/api/box-office/desk/performances.get.ts', exempt: 'reads tonight\'s programme; nothing is written' },
  { route: 'server/api/box-office/desk/search.get.ts', exempt: 'reads bookings against a performance; nothing is written' },
  { route: 'server/api/box-office/desk/scan.post.ts', exempt: 'resolves a scanned code to a booking; nothing is written' },
  { route: 'server/api/box-office/desk/reservations/[id].get.ts', exempt: 'reads one booking; nothing is written' },
  {
    route: 'server/api/box-office/desk/reservations/[id]/collect.post.ts',
    actions: ['reservation.collected'],
    via: ['server/utils/desk-collection.ts'],
  },
  {
    route: 'server/api/box-office/desk/reservations/[id]/tickets/[ticketId]/refund.post.ts',
    actions: ['ticket.refunded'],
    via: ['server/utils/refunds.ts'],
  },
  {
    route: 'server/api/box-office/desk/reservations/[id]/cancel.post.ts',
    actions: ['reservation.cancelled.staff'],
    via: ['server/utils/refunds.ts'],
  },

  // Module E: show night

  {
    route: 'server/api/tonight/authority.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/duty-manager.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/report.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/age-checks/index.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/age-checks/index.post.ts',
    actions: ['age-check.logged', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/age-checks/[id]/supersede.post.ts',
    actions: ['age-check.superseded', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/incidents/index.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/incidents/index.post.ts',
    actions: ['incident.logged', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/incidents/near-miss.post.ts',
    actions: ['incident.logged', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/incidents/[id]/supersede.post.ts',
    actions: ['incident.superseded', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/incidents/[id]/review.post.ts',
    actions: ['incident.reviewed', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/checklist/index.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/checklist/[stampId]/tick.post.ts',
    actions: ['checklist.ticked', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/checklist/[stampId]/exempt.post.ts',
    actions: ['checklist.exempted', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/checklist/close.post.ts',
    actions: ['checklist.closed', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  { route: 'server/api/admin/checklist/index.get.ts', exempt: 'reads every venue\'s checklist, including a venue with none' },
  { route: 'server/api/admin/checklist/items/index.get.ts', exempt: 'reads a venue\'s checklist items, including a venue with none' },
  { route: 'server/api/admin/checklist/items/index.post.ts', actions: ['checklist-item.created'] },
  { route: 'server/api/admin/checklist/items/[id]/index.put.ts', actions: ['checklist-item.updated'] },
  { route: 'server/api/admin/checklist/items/[id]/status.post.ts', actions: ['checklist-item.retired', 'checklist-item.reinstated'] },
  { route: 'server/api/admin/venues/emergency.get.ts', exempt: 'reads every venue\'s current emergency card, including a venue with none' },
  { route: 'server/api/admin/venues/[id]/emergency.put.ts', actions: ['emergency-card.updated'] },
  {
    route: 'server/api/tonight/emergency.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  { route: 'server/api/admin/safety/severities/index.get.ts', exempt: 'reads the fixed four-severity routing table' },
  { route: 'server/api/admin/safety/severities/[severity]/index.put.ts', actions: ['incident-severity.routing-changed'] },
  { route: 'server/api/admin/safety/open-items.get.ts', exempt: 'reads the open-items list, gated by the safety officer\'s own permission' },
  { route: 'server/api/admin/safety/incidents/[id]/close.post.ts', actions: ['incident-followup.closed'] },
  { route: 'server/api/admin/age-checks/export.get.ts', actions: ['age-checks.exported'] },
  {
    route: 'server/api/tonight/board/code.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  { route: 'server/api/board/join.post.ts', actions: ['board.joined'] },
  { route: 'server/api/board/config.get.ts', exempt: 'reads the active milestone types and presets, gated by the caller\'s own device credential' },
  { route: 'server/api/board/messages/index.get.ts', exempt: 'reads tonight\'s board, gated by the caller\'s own device credential' },
  { route: 'server/api/board/messages/index.post.ts', actions: ['board.message-posted'] },
  { route: 'server/api/board/messages/[id]/supersede.post.ts', actions: ['board.message-superseded'] },
  { route: 'server/api/board/messages/[id]/acknowledge.post.ts', exempt: 'an idempotent, high-volume presence fact, not a privileged mutation' },
  {
    route: 'server/api/tonight/board/reset.post.ts',
    actions: ['board.reset', 'night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/tonight/board/messages.get.ts',
    actions: ['night.officer-bypass'],
    via: ['server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  { route: 'server/api/admin/backstage/milestone-types/index.get.ts', exempt: 'reads every milestone type, including a retired one' },
  { route: 'server/api/admin/backstage/milestone-types/index.post.ts', actions: ['backstage-milestone-type.created'] },
  { route: 'server/api/admin/backstage/milestone-types/[id]/index.put.ts', actions: ['backstage-milestone-type.updated'] },
  { route: 'server/api/admin/backstage/milestone-types/[id]/status.post.ts', actions: ['backstage-milestone-type.retired', 'backstage-milestone-type.reinstated'] },
  { route: 'server/api/admin/backstage/presets/index.get.ts', exempt: 'reads every preset, including a retired one' },
  { route: 'server/api/admin/backstage/presets/index.post.ts', actions: ['backstage-preset.created'] },
  { route: 'server/api/admin/backstage/presets/[id]/index.put.ts', actions: ['backstage-preset.updated'] },
  { route: 'server/api/admin/backstage/presets/[id]/status.post.ts', actions: ['backstage-preset.retired', 'backstage-preset.reinstated'] },
  { route: 'server/api/admin/rota/templates/index.get.ts', exempt: 'reads every venue\'s template, including the venues that have none' },
  {
    route: 'server/api/admin/rota/templates/[venueId]/index.put.ts',
    actions: ['shift-template.created', 'shift-template.updated'],
  },
  { route: 'server/api/admin/rota/templates/[venueId]/index.delete.ts', actions: ['shift-template.removed'] },
  { route: 'server/api/admin/rota/templates/[venueId]/stamp.post.ts', actions: ['shift.stamped'] },
  { route: 'server/api/rota/shifts.get.ts', exempt: 'reads the open-shift list, gated live against your own training records' },
  { route: 'server/api/rota/mine.get.ts', exempt: 'reads your own shifts' },
  { route: 'server/api/rota/shifts/[id]/claim.post.ts', actions: ['shift.claimed'] },
  { route: 'server/api/rota/shifts/[id]/release.post.ts', actions: ['shift.released'] },
  { route: 'server/api/rota/shifts/[id]/dismiss.post.ts', actions: ['shift.dismissed'] },
  { route: 'server/api/admin/rota/approvals/index.get.ts', exempt: 'reads the queued claims waiting on a decision' },
  { route: 'server/api/admin/rota/approvals/[id]/approve.post.ts', actions: ['shift.confirmed'] },
  { route: 'server/api/admin/rota/approvals/[id]/decline.post.ts', actions: ['shift.declined'] },
  { route: 'server/api/admin/rota/shifts.get.ts', exempt: 'reads the open and declined shifts an officer has to fill by hand' },
  { route: 'server/api/admin/rota/shifts/[id]/assign.post.ts', actions: ['shift.reassigned'] },
  { route: 'server/api/admin/rota/shifts/[id]/candidates.get.ts', exempt: 'reads who might be assigned, scoped to rota.write' },

  // Module F: bar

  { route: 'server/api/admin/bar/categories/index.get.ts', exempt: 'reads the till\'s layout' },
  { route: 'server/api/admin/bar/categories/index.post.ts', actions: ['bar.category.created'] },
  { route: 'server/api/admin/bar/categories/[id]/index.put.ts', actions: ['bar.category.updated'] },
  { route: 'server/api/admin/bar/categories/[id]/prices.post.ts', actions: ['bar.category.price.set'] },
  { route: 'server/api/admin/bar/products/index.get.ts', exempt: 'reads the products, retired ones included' },
  { route: 'server/api/admin/bar/products/index.post.ts', actions: ['bar.product.created'] },
  { route: 'server/api/admin/bar/products/[id]/index.put.ts', actions: ['bar.product.updated'] },
  { route: 'server/api/admin/bar/products/[id]/status.post.ts', actions: ['bar.product.status.changed'] },
  { route: 'server/api/admin/bar/products/[id]/index.delete.ts', actions: ['bar.product.deleted'] },
  { route: 'server/api/admin/bar/products/[id]/variants.get.ts', exempt: 'reads the sizes a product sells at' },
  { route: 'server/api/admin/bar/variants/index.post.ts', actions: ['bar.variant.created'] },
  { route: 'server/api/admin/bar/variants/[id]/index.put.ts', actions: ['bar.variant.updated'] },
  { route: 'server/api/admin/bar/variants/[id]/status.post.ts', actions: ['bar.variant.status.changed'] },
  { route: 'server/api/admin/bar/variants/[id]/index.delete.ts', actions: ['bar.variant.deleted'] },
  { route: 'server/api/admin/bar/variants/[id]/components.put.ts', actions: ['bar.variant.recipe.changed'] },
  { route: 'server/api/admin/bar/variants/[id]/choice.put.ts', actions: ['bar.variant.choice.changed'] },
  { route: 'server/api/admin/bar/variants/[id]/prices.get.ts', exempt: 'reads the price history of one serving size' },
  { route: 'server/api/admin/bar/variants/[id]/prices.post.ts', actions: ['bar.variant.price.set'] },
  { route: 'server/api/admin/bar/choice-groups/index.get.ts', exempt: 'reads the choice groups a variant may attach' },
  { route: 'server/api/admin/bar/choice-groups/index.post.ts', actions: ['bar.choice-group.created'] },
  { route: 'server/api/admin/bar/discounts/index.get.ts', exempt: 'reads every discount, active and retired' },
  { route: 'server/api/admin/bar/discounts/index.post.ts', actions: ['bar.discount.created'] },
  { route: 'server/api/admin/bar/discounts/[id]/index.put.ts', actions: ['bar.discount.updated'] },
  { route: 'server/api/admin/bar/discounts/[id]/status.post.ts', actions: ['bar.discount.status.changed'] },
  { route: 'server/api/admin/bar/items/index.get.ts', exempt: 'reads the stocked items and what is on hand' },
  { route: 'server/api/admin/bar/items/index.post.ts', actions: ['bar.item.created'] },
  { route: 'server/api/admin/bar/items/[id]/index.put.ts', actions: ['bar.item.updated'] },
  { route: 'server/api/admin/bar/items/[id]/status.post.ts', actions: ['bar.item.status.changed'] },
  { route: 'server/api/admin/bar/items/[id]/index.delete.ts', actions: ['bar.item.deleted'] },
  { route: 'server/api/admin/bar/stocktakes/index.get.ts', exempt: 'reads stocktake history' },
  { route: 'server/api/admin/bar/stocktakes/index.post.ts', actions: ['bar.stocktake.opened'] },
  { route: 'server/api/admin/bar/stocktakes/[id]/index.get.ts', exempt: 'reads one stocktake and its lines' },
  { route: 'server/api/admin/bar/stocktakes/[id]/counts.put.ts', actions: ['bar.stocktake.counted'] },
  { route: 'server/api/admin/bar/stocktakes/[id]/apply.post.ts', actions: ['bar.stocktake.applied'] },
  { route: 'server/api/admin/bar/order-list/index.get.ts', exempt: 'reads shortfalls against par, advisory only' },
  { route: 'server/api/admin/bar/order-list/export.get.ts', exempt: 'reads the same shortfalls as CSV' },
  { route: 'server/api/admin/bar/reports/index.get.ts', exempt: 'reads sales, GP, variance, comps and discounts, writing nothing' },
  { route: 'server/api/admin/bar/reports/export.get.ts', actions: ['bar.report.exported'] },
  { route: 'server/api/admin/bar/tabs.get.ts', exempt: 'reads who still owes a balance, writing nothing' },
  {
    route: 'server/api/admin/bar/tab-charges/[id]/void.post.ts',
    actions: ['bar.tab-charge.voided'],
    via: ['server/utils/tab-settlement.ts'],
  },
  { route: 'server/api/admin/bar/movements/index.get.ts', exempt: 'reads the movement history' },
  {
    route: 'server/api/admin/bar/movements/index.post.ts',
    exempt: 'the movement is the record: it stamps its own actor and time, cannot be edited or deleted, and a correction supersedes it (0010, F-114 criteria 4 and 5)',
  },
  { route: 'server/api/till/index.get.ts', exempt: 'reads tonight\'s session for a venue, opening nothing' },
  { route: 'server/api/till/index.post.ts', actions: ['bar.till.opened'] },
  { route: 'server/api/till/close.post.ts', actions: ['bar.till.closed'] },
  { route: 'server/api/till/products.get.ts', exempt: 'reads what the till may sell right now, writing nothing' },
  { route: 'server/api/till/discounts.get.ts', exempt: 'reads the active discounts the till may apply, writing nothing' },
  { route: 'server/api/till/tab-holders.get.ts', exempt: 'reads who the till may charge a sale to, writing nothing' },
  { route: 'server/api/till/price.post.ts', exempt: 'prices a basket against live prices; nothing is written until F-104 and F-105 land the sale write' },
  { route: 'server/api/till/sale.post.ts', actions: ['bar.till.sale', 'age-check.logged', 'bar.tab.cap-overridden'], via: ['server/utils/sale.ts'] },
  { route: 'server/api/till/comp-requests/index.get.ts', exempt: 'reads tonight\'s pending comp requests, writing nothing' },
  { route: 'server/api/till/comp-requests/index.post.ts', actions: ['bar.comp-request.created'], via: ['server/utils/comps.ts'] },
  {
    route: 'server/api/till/comp-requests/[id]/approve.post.ts',
    actions: ['bar.comp-request.approved', 'night.officer-bypass'],
    via: ['server/utils/comps.ts', 'server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  {
    route: 'server/api/till/comp-requests/[id]/decline.post.ts',
    actions: ['bar.comp-request.declined', 'night.officer-bypass'],
    via: ['server/utils/comps.ts', 'server/utils/night-authority.ts', 'shared/utils/night-authority.ts'],
  },
  { route: 'server/api/till/comp-requests/[id]/sale.post.ts', actions: ['bar.till.sale', 'age-check.logged'], via: ['server/utils/sale.ts'] },
  { route: 'server/api/till/tab-settlements/index.get.ts', exempt: 'reads one holder\'s outstanding charges, writing nothing' },
  {
    route: 'server/api/till/tab-settlements/index.post.ts',
    actions: ['bar.tab.settled'],
    via: ['server/utils/tab-settlement.ts'],
  },
  { route: 'server/api/account/tab.get.ts', exempt: 'reads your own tab' },

  // Module G: training

  {
    route: 'server/api/admin/training/external-certificates/index.post.ts',
    actions: ['record.external-certificate'],
  },
  { route: 'server/api/admin/training/departments/index.get.ts', exempt: 'reads the department vocabulary' },
  { route: 'server/api/admin/training/departments/index.post.ts', actions: ['department.created'] },
  { route: 'server/api/admin/training/departments/[code]/index.put.ts', actions: ['department.updated'] },
  { route: 'server/api/admin/training/departments/[code]/leads.post.ts', actions: ['department.lead.assigned'] },
  { route: 'server/api/admin/training/leads/[id].delete.ts', actions: ['department.lead.removed'] },
  { route: 'server/api/admin/training/modules/index.get.ts', exempt: 'reads the training catalogue' },
  { route: 'server/api/admin/training/modules/index.post.ts', actions: ['module.created'] },
  { route: 'server/api/admin/training/modules/[id]/index.put.ts', actions: ['module.updated'] },
  { route: 'server/api/admin/training/records/index.get.ts', exempt: 'reads one person\'s training history' },
  { route: 'server/api/training/records.get.ts', exempt: 'reads your own training records' },
  { route: 'server/api/training/modules.get.ts', exempt: 'reads the member-facing catalogue' },
  { route: 'server/api/training/next.get.ts', exempt: 'reads what you could take next, all from your own records' },
  { route: 'server/api/training/requests/index.get.ts', exempt: 'reads what you asked for' },
  { route: 'server/api/training/requests/index.post.ts', exempt: 'a demand signal about yourself, carrying no authority' },
  { route: 'server/api/training/requests/[id].delete.ts', exempt: 'withdraws your own ask' },
  { route: 'server/api/admin/training/requests/index.get.ts', exempt: 'reads the demand board' },
  { route: 'server/api/admin/training/requests/[id]/decline.post.ts', actions: ['request.declined'] },
  { route: 'server/api/admin/training/sessions/[id]/register.get.ts', exempt: 'reads the register a trainer is about to mark' },
  { route: 'server/api/admin/training/sessions/[id]/open-register.post.ts', actions: ['register.opened'] },
  { route: 'server/api/admin/training/sessions/[id]/attendees.post.ts', actions: ['session.attendee.added'] },
  { route: 'server/api/admin/training/sessions/[id]/cancel.post.ts', actions: ['session.cancelled'] },
  {
    route: 'server/api/admin/training/sessions/[id]/marks.post.ts',
    actions: ['register.corrected'],
    via: ['server/utils/training-register.ts'],
  },
  {
    route: 'server/api/admin/training/attendees/lookup.post.ts',
    actions: ['account.created.console'],
    via: ['server/utils/accounts.ts'],
  },
  {
    route: 'server/api/admin/training/sessions/[id]/mark.post.ts',
    actions: ['register.marked'],
    via: ['server/utils/training-register.ts'],
  },
  {
    route: 'server/api/admin/training/sessions/[id]/modules.put.ts',
    actions: ['session.modules.changed', 'register.freeze.released'],
  },
  { route: 'server/api/admin/training/modules/[id]/prerequisites.post.ts', actions: ['prerequisite.added'] },
  { route: 'server/api/admin/training/prerequisites/[id].delete.ts', actions: ['prerequisite.removed'] },
  {
    route: 'server/api/admin/training/signoffs/index.post.ts',
    actions: ['record.signed-off', 'record.signoff.unbounded'],
  },
  { route: 'server/api/admin/training/records/[id]/revoke.post.ts', actions: ['record.revoked'] },
  { route: 'server/api/admin/training/sessions/index.post.ts', actions: ['session.scheduled'] },
  { route: 'server/api/admin/training/sessions/index.get.ts', exempt: 'reads the scheduled sessions' },
  {
    route: 'server/api/admin/training/deliveries/preview.post.ts',
    exempt: 'the dry-run for a retrospective log; it writes nothing at all',
  },
  {
    route: 'server/api/admin/training/deliveries/index.post.ts',
    actions: ['record.delivery-logged'],
  },
  {
    route: 'server/api/admin/training/sessions/[id]/capacity.post.ts',
    actions: ['session.capacity.changed'],
  },
  { route: 'server/api/training/sessions/index.get.ts', exempt: 'reads the sessions open to you, and where you stand on each' },
  {
    route: 'server/api/training/sessions/[id]/signup.post.ts',
    exempt: 'joins a queue about yourself; the place it confers is derived, not granted',
  },
  {
    route: 'server/api/training/sessions/[id]/signup.delete.ts',
    exempt: 'leaves a queue you joined yourself, taking no authority with it',
  },

  // Module H: communications

  { route: 'server/api/admin/notifications/trouble.get.ts', exempt: 'reads the message log' },
  { route: 'server/api/account/notifications.get.ts', exempt: 'reads your own notification preferences and inbox' },
  {
    route: 'server/api/account/notifications.put.ts',
    actions: ['notifications.preference.changed'],
    via: ['server/utils/notification-preferences.ts'],
  },

  // Module I: finance

  // Module J: governance

  { route: 'server/api/admin/audit/export.get.ts', actions: ['audit.exported'] },
  {
    route: 'server/api/admin/audit/index.post.ts',
    actions: ['manual.role.granted', 'manual.role.revoked', 'manual.account.disabled', 'manual.account.enabled'],
    via: ['shared/utils/audit-actions.ts'],
  },
  { route: 'server/api/admin/fellowships/[id]/revoke.post.ts', actions: ['fellowship.revoked'] },
  { route: 'server/api/admin/fellowships/index.post.ts', actions: ['fellowship.awarded'] },
  { route: 'server/api/admin/config/[key].put.ts', actions: ['config.changed'] },

  // Module K: platform

  { route: 'server/api/admin/backups/index.get.ts', exempt: 'reads drill status for the dashboard' },
  { route: 'server/api/admin/backups/drills/index.get.ts', exempt: 'reads recorded drills' },
  { route: 'server/api/admin/backups/drills/index.post.ts', actions: ['backup.drill-recorded'] },

  // Development only, and absent from a build: nuxt.config excludes both files (K-124).
  {
    route: 'server/api/dev/seed.post.ts',
    actions: ['account.registered', 'account.erased.system'],
    via: ['server/utils/dev.ts', 'server/utils/accounts.ts', 'server/utils/erasure.ts'],
  },
  { route: 'server/api/dev/sweep-requests.post.ts', actions: ['room.request.expired'], via: ['server/utils/room-requests.ts'] },
  { route: 'server/api/dev/remind-rooms.post.ts', exempt: 'sends a reminder; the send is recorded in notification_log' },
  { route: 'server/api/dev/remind-shifts.post.ts', exempt: 'sends a reminder; the send is recorded in notification_log' },
  { route: 'server/api/dev/escalate-rota.post.ts', exempt: 'sends a digest; the send is recorded in notification_log' },
  { route: 'server/api/dev/sign-in-as.post.ts', exempt: 'a development sign-in with no password, in no build' },
]
